### ISSUE TITLE
boss ai 

### ISSUE THREAD

**Issue by LawCosmos** [Wayl123/This-Is-Nightmare-Project#4]
making the boss vanish and reappear at the 3 parts of the map with a random time and mechanic tied to it

**Comment by Wayl123** [comment]
boss mechanics 
regular moveset that happens always:
slow half size of the boss bullets boss doesnt shoot a lot of them but they by pass the map very slowly causing problems over time when u are moving 
spawns 2-4 adds with a cap of 4 around 
phase one starts at 75% hp
phase 1- boss turn the bullets into a bullet hell instead of fast they go randomly all arond the map touhou style 
phase 2 50% hp the touhou bullets stop but the boss spawns a lot more adds enough to having u to kill adds to be able to move safely 
phase 3 25% hp the boss becomes immune both the bullet hell and more adds happen together and u have to break 4 pillars that spawned in the 4 corners of the map

**Comment by Wayl123** [comment]
Since law just doesn't put it in the issue no matter what.

**Comment by LisicaQ** [comment]
1.25 the size of the player (roughly)
